import tkinter as tk
from tkinter import ttk

# =========================
# CONTROL UNIT LOGIC
# =========================

CONTROL_SIGNALS = [
    "RegWrite", "MemRead", "MemWrite",
    "ALUSrc", "Branch", "MemToReg", "ALUOp"
]

INSTRUCTION_SET = {
    "ADD": {
        "RegWrite": 1, "MemRead": 0, "MemWrite": 0,
        "ALUSrc": 0, "Branch": 0, "MemToReg": 0, "ALUOp": "ADD"
    },
    "SUB": {
        "RegWrite": 1, "MemRead": 0, "MemWrite": 0,
        "ALUSrc": 0, "Branch": 0, "MemToReg": 0, "ALUOp": "SUB"
    },
    "LOAD": {
        "RegWrite": 1, "MemRead": 1, "MemWrite": 0,
        "ALUSrc": 1, "Branch": 0, "MemToReg": 1, "ALUOp": "ADD"
    },
    "STORE": {
        "RegWrite": 0, "MemRead": 0, "MemWrite": 1,
        "ALUSrc": 1, "Branch": 0, "MemToReg": "X", "ALUOp": "ADD"
    },
    "BEQ": {
        "RegWrite": 0, "MemRead": 0, "MemWrite": 0,
        "ALUSrc": 0, "Branch": 1, "MemToReg": "X", "ALUOp": "SUB"
    }
}

# =========================
# GUI APPLICATION
# =========================

class ControlUnitVisualizer:
    def __init__(self, root):
        self.root = root
        root.title("Control Unit Logic Visualizer")
        root.geometry("750x500")

        self.create_widgets()

    def create_widgets(self):
        # Instruction Selection
        tk.Label(self.root, text="Select Instruction", font=("Arial", 11)).pack(pady=5)

        self.instr_var = tk.StringVar()
        self.instr_box = ttk.Combobox(
            self.root,
            textvariable=self.instr_var,
            values=list(INSTRUCTION_SET.keys()),
            state="readonly"
        )
        self.instr_box.pack()
        self.instr_box.bind("<<ComboboxSelected>>", self.update_signals)

        # Control Signal Table
        tk.Label(self.root, text="Control Signals", font=("Arial", 11)).pack(pady=10)

        self.table = ttk.Treeview(self.root, columns=("Value"), height=10)
        self.table.heading("#0", text="Signal")
        self.table.heading("Value", text="Value")
        self.table.pack(fill="both", padx=20, expand=True)

        # Description
        self.desc = tk.Label(
            self.root,
            text="Select an instruction to visualize control unit output",
            relief="sunken",
            anchor="w"
        )
        self.desc.pack(fill="x", side="bottom")

    def update_signals(self, event=None):
        instr = self.instr_var.get()
        signals = INSTRUCTION_SET[instr]

        self.table.delete(*self.table.get_children())

        for sig in CONTROL_SIGNALS:
            self.table.insert("", "end", text=sig, values=(signals[sig],))

        self.desc.config(
            text=f"Instruction: {instr} | Control signals generated by Control Unit"
        )


# =========================
# MAIN
# =========================

if __name__ == "__main__":
    root = tk.Tk()
    app = ControlUnitVisualizer(root)
    root.mainloop()
